# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Schifman Ben/Documents/UofA/Senior 2016-2017/Fall 2016/574 ECE/Assignments/Assignment1/Assignment1/Assignment1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Schifman Ben/Documents/UofA/Senior 2016-2017/Fall 2016/574 ECE/Assignments/Assignment1/Assignment1/Assignment1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Schifman Ben/Documents/UofA/Senior 2016-2017/Fall 2016/574 ECE/Assignments/Assignment1/Assignment1/Assignment1.srcs/sources_1/new/ADD.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ADD2 -part xc7a100tcsg324-3


write_checkpoint -force -noxdef ADD2.dcp

catch { report_utilization -file ADD2_utilization_synth.rpt -pb ADD2_utilization_synth.pb }
